# Файл main.yml
name: Main Taski Workflow
on:
  push:
    branches:
      - main
jobs:
  checkout-and-print-tree:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      # Устанавливаем утилиту tree
      - name: Install tree utility
        run: sudo apt-get install -y tree

      # Теперь эта команда сработает
      - name: Print project tree
        run: tree .